### ISSUE TITLE
Different version of jQuery clash when using CMS Ucoz

### ISSUE THREAD

**Issue by Levelleor** [simov/simplr-smoothscroll#18]
I get an error: 
Uncaught TypeError: $.srSmoothscroll is not a function

I tried a lot of different stuff so far and don't know what to do next to fix this. 

Thx for attention in advance!

**Comment by simov** [comment]
You have to include the plugin before you can use it.

**Comment by Levelleor** [comment]
You mean I`m dumb? :) (<-that's a joke)

<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript" charset="utf-8"></script>

<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.0.6/jquery.mousewheel.min.js" type="text/javascript" charset="utf-8"></script>

<script src="/lib/jquery.simplr.smoothscroll.js" type="text/javascript" charset="utf-8"></script>

<script src="/lib/jquery.easing.compatibility.js" type="text/javascript" charset="utf-8"></script>

<script src="/lib/jquery.easing.1.3.js" type="text/javascript" charset="utf-8"></script>

  <script type="text/javascript" charset="utf-8">
    $(function () {
      $.srSmoothscroll()
    })
  </script>

**Comment by simov** [comment]
No, I don't mean that. Can you try with both the minified and the regular version? I'm suspecting that something may be wrong with the minified one.

**Comment by Levelleor** [comment]
What is the minified version? 
Also, I want to add that local version is working, and right now I am on CMS, but I still can't find out the problem. Someone wrote about 100% height, I have it, but it swear before I was able to slide...

**Comment by Levelleor** [comment]
Here is what I include just for this plugin. On local version this works... 
![image](https://cloud.githubusercontent.com/assets/11915185/9027206/ea8783c6-3900-11e5-94b5-19f5d91c93d6.png)

**Comment by simov** [comment]
That's weird, are you sure you have the latest version of the plugin in your `lib` folder?

**Comment by Levelleor** [comment]
I think so.. I downloaded it yesterday!

**Comment by simov** [comment]
That's the code from the demo:

``` html
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript" charset="utf-8"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.0.6/jquery.mousewheel.min.js" type="text/javascript" charset="utf-8"></script>
<script src="../lib/jquery.simplr.smoothscroll.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript" charset="utf-8">
    $(function () {
      $.srSmoothscroll()
    })
</script>
```

THB I'm out of ideas at this point.

**Comment by Levelleor** [comment]
Ok, I made it work! 
My CMS was including old JQuery library, which was really hard to remove... 
And now I have another problem which is completely different story xD 
Thank you for help anyway!

**Comment by simov** [comment]
Can you provide a little bit more background info on your setup and how exactly you fixed it? I want to change the title of this issue, so that it can help others with similar issue.

**Comment by Levelleor** [comment]
I am using CMS called Ucoz, which I think no one knows about here, but it includes JQuery 1.7.2, which conflicts with your plugin.
Other steps are too complex to talk about, so just remember to check if you have only one library of JQuery on the page and if should be version 1.8.3 or higher.

Also, I apologize for mistakes here xD (edit: fix english mistakes from younger myself :))
