### ISSUE TITLE
Very fast scroll speed on MacBook Pro with native touchpad

### ISSUE THREAD

**Issue by ghost** [simov/simplr-smoothscroll#7]
There is a issue with your script on MacBook Pro. The scroll speed is really fast when using touchpad on MacBook Pro. Please fix it. Our team made a temporary solution to not initialize your script on MacBook Pro. So here is a code:

var platform = window.navigator.platform;
if (!(platform === 'MacIntel' || platform === 'MacPPC')) {
      $.srSmoothscroll(
          ..........
      );
  }

**Comment by dhanilkumart** [comment]
Hi,
I have added the above code and it is working perfect in both desktop and macbook but it s showing an error, how can i fix this??


```
ReferenceError: mobile is not defined
if (!mobile && MacBookPro) {
```
